# Generated by Django 5.2.6 on 2026-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the donor.', max_length=100)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('COMPLETED', 'Completed')], db_index=True, default='ELIGIBLE', help_text='Current status in the donation pipeline.', max_length=10)),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('GU', 'Gujarati')], default='HI', help_text='Preferred display language for celebration messages.', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
            },
        ),
    ]
